apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: secrets-store-csi-gcp
  project: api-team
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterType
      value: gke
  resourceQuotas: {}
