apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: eks-presales
  project: api-team
spec:
  base:
    name: minimal
    version: 1.28.0
  costProfile:
    name: default-cost-profile-aws
    version: version-1673434684
  customAddons:
  - name: autoscaler-addon
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers:
        aws: true
    enableCsiSecretStore: true
    enableMonitoring: true
  drift:
    action: Notify
    enabled: true
  placement:
    autoPublish: true
    fleetValues:
    - eks-presales
  type: custom
  version: v1
